import { SafeGitHubRepo } from '../app/core/models/github-repo.model';

const now = new Date();
const months = (n: number) => new Date(now.getTime() - n * 30 * 24 * 60 * 60 * 1000).toISOString();

export const FAKE_REPOS: SafeGitHubRepo[] = [
  {
    id: 1,
    name: 'portfolio-site',
    fullName: 'demo/portfolio-site',
    description: 'My personal developer portfolio — built with Angular and deployed on Vercel.',
    htmlUrl: 'https://github.com/demo/portfolio-site',
    private: false,
    fork: false,
    archived: false,
    disabled: false,
    visibility: 'public',
    language: 'TypeScript',
    stargazersCount: 34,
    forksCount: 7,
    openIssuesCount: 2,
    defaultBranch: 'main',
    topics: ['angular', 'portfolio', 'typescript'],
    createdAt: months(18),
    updatedAt: months(1),
    pushedAt: months(1),
    size: 4820,
    hasIssues: true,
    hasProjects: false,
    hasWiki: false,
    licenseName: 'MIT',
  },
  {
    id: 2,
    name: 'codeshelf',
    fullName: 'demo/codeshelf',
    description: 'A localhost GitHub repository review and management tool.',
    htmlUrl: 'https://github.com/demo/codeshelf',
    private: false,
    fork: false,
    archived: false,
    disabled: false,
    visibility: 'public',
    language: 'TypeScript',
    stargazersCount: 12,
    forksCount: 3,
    openIssuesCount: 0,
    defaultBranch: 'main',
    topics: ['github', 'developer-tools', 'angular', 'nodejs'],
    createdAt: months(3),
    updatedAt: months(0),
    pushedAt: months(0),
    size: 2100,
    hasIssues: true,
    hasProjects: false,
    hasWiki: false,
    licenseName: 'MIT',
  },
  {
    id: 3,
    name: 'express-api-starter',
    fullName: 'demo/express-api-starter',
    description: 'Minimal Express.js REST API template with JWT auth and Mongoose.',
    htmlUrl: 'https://github.com/demo/express-api-starter',
    private: false,
    fork: false,
    archived: false,
    disabled: false,
    visibility: 'public',
    language: 'JavaScript',
    stargazersCount: 88,
    forksCount: 22,
    openIssuesCount: 5,
    defaultBranch: 'main',
    topics: ['express', 'nodejs', 'api', 'starter'],
    createdAt: months(30),
    updatedAt: months(4),
    pushedAt: months(4),
    size: 1240,
    hasIssues: true,
    hasProjects: false,
    hasWiki: false,
    licenseName: 'MIT',
  },
  {
    id: 4,
    name: 'old-jquery-thing',
    fullName: 'demo/old-jquery-thing',
    description: null,
    htmlUrl: 'https://github.com/demo/old-jquery-thing',
    private: false,
    fork: false,
    archived: false,
    disabled: false,
    visibility: 'public',
    language: 'JavaScript',
    stargazersCount: 0,
    forksCount: 0,
    openIssuesCount: 0,
    defaultBranch: 'master',
    topics: [],
    createdAt: months(60),
    updatedAt: months(48),
    pushedAt: months(48),
    size: 320,
    hasIssues: false,
    hasProjects: false,
    hasWiki: false,
    licenseName: null,
  },
  {
    id: 5,
    name: 'react-dashboard-fork',
    fullName: 'demo/react-dashboard-fork',
    description: 'Forked from someone else\'s dashboard — adapted for my use.',
    htmlUrl: 'https://github.com/demo/react-dashboard-fork',
    private: false,
    fork: true,
    archived: false,
    disabled: false,
    visibility: 'public',
    language: 'JavaScript',
    stargazersCount: 1,
    forksCount: 0,
    openIssuesCount: 0,
    defaultBranch: 'main',
    topics: [],
    createdAt: months(14),
    updatedAt: months(13),
    pushedAt: months(13),
    size: 8900,
    hasIssues: false,
    hasProjects: false,
    hasWiki: false,
    licenseName: null,
  },
  {
    id: 6,
    name: 'archived-boot-camp-project',
    fullName: 'demo/archived-boot-camp-project',
    description: 'First full-stack project from bootcamp. Kept for nostalgia.',
    htmlUrl: 'https://github.com/demo/archived-boot-camp-project',
    private: false,
    fork: false,
    archived: true,
    disabled: false,
    visibility: 'public',
    language: 'HTML',
    stargazersCount: 0,
    forksCount: 0,
    openIssuesCount: 0,
    defaultBranch: 'master',
    topics: [],
    createdAt: months(48),
    updatedAt: months(48),
    pushedAt: months(48),
    size: 540,
    hasIssues: false,
    hasProjects: false,
    hasWiki: false,
    licenseName: null,
  },
  {
    id: 7,
    name: 'client-project-alpha',
    fullName: 'demo/client-project-alpha',
    description: 'Private client work — NDA applies.',
    htmlUrl: 'https://github.com/demo/client-project-alpha',
    private: true,
    fork: false,
    archived: false,
    disabled: false,
    visibility: 'private',
    language: 'TypeScript',
    stargazersCount: 0,
    forksCount: 0,
    openIssuesCount: 3,
    defaultBranch: 'main',
    topics: [],
    createdAt: months(8),
    updatedAt: months(1),
    pushedAt: months(1),
    size: 6700,
    hasIssues: true,
    hasProjects: true,
    hasWiki: false,
    licenseName: null,
  },
  {
    id: 8,
    name: 'dotfiles',
    fullName: 'demo/dotfiles',
    description: 'My shell config, aliases, and editor settings.',
    htmlUrl: 'https://github.com/demo/dotfiles',
    private: true,
    fork: false,
    archived: false,
    disabled: false,
    visibility: 'private',
    language: 'Shell',
    stargazersCount: 0,
    forksCount: 0,
    openIssuesCount: 0,
    defaultBranch: 'main',
    topics: ['dotfiles', 'shell'],
    createdAt: months(24),
    updatedAt: months(2),
    pushedAt: months(2),
    size: 180,
    hasIssues: false,
    hasProjects: false,
    hasWiki: false,
    licenseName: null,
  },
  {
    id: 9,
    name: 'interview-prep',
    fullName: 'demo/interview-prep',
    description: null,
    htmlUrl: 'https://github.com/demo/interview-prep',
    private: true,
    fork: false,
    archived: false,
    disabled: false,
    visibility: 'private',
    language: 'Python',
    stargazersCount: 0,
    forksCount: 0,
    openIssuesCount: 0,
    defaultBranch: 'main',
    topics: [],
    createdAt: months(6),
    updatedAt: months(3),
    pushedAt: months(3),
    size: 440,
    hasIssues: false,
    hasProjects: false,
    hasWiki: false,
    licenseName: null,
  },
  {
    id: 10,
    name: 'no-description-public',
    fullName: 'demo/no-description-public',
    description: null,
    htmlUrl: 'https://github.com/demo/no-description-public',
    private: false,
    fork: false,
    archived: false,
    disabled: false,
    visibility: 'public',
    language: 'Go',
    stargazersCount: 2,
    forksCount: 0,
    openIssuesCount: 0,
    defaultBranch: 'main',
    topics: [],
    createdAt: months(10),
    updatedAt: months(5),
    pushedAt: months(5),
    size: 680,
    hasIssues: true,
    hasProjects: false,
    hasWiki: false,
    licenseName: null,
  },
];
